# Generated by Django 3.0.8 on 2020-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200716_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titre_slug',
            field=models.SlugField(editable=False, max_length=300, null=True),
        ),
    ]
