# Generated by Django 3.0.8 on 2020-07-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200722_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
